# Generated by Django 5.2.8 on 2025-11-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=120, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('tiempo_preparacion_min', models.IntegerField()),
                ('calorias', models.IntegerField()),
                ('es_vegetariano', models.BooleanField(default=False)),
                ('nivel_picante', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
